<a href="https://colab.research.google.com/github/ArlethSosa/Space-Y/blob/main/SPACE_Y_Parte_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Space Y**
## Parte 3. Analisis exploratorio de los datos con SQL

In [1]:
!pip install sqlalchemy==1.3.9
!pip install ipython-sql
!pip install ipython-sql prettytable
%load_ext sql

Collecting sqlalchemy==1.3.9
  Downloading SQLAlchemy-1.3.9.tar.gz (6.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 18.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: sqlalchemy
  Building wheel for sqlalchemy (setup.py) ... done
  Created wheel for sqlalchemy: filename=SQLAlchemy-1.3.9-cp312-cp312-linux_x86_64.whl size=1196050 sha256=68989be889c18d103129eccf29bc608892d8a4c1765d004f7465c35b0c0fcd5e
  Stored in directory: /root/.cache/pip/wheels/b3/1c/42/0e26b8d512adc6bce10ff71a05229366b4ccec641cd3b42111
Successfully built sqlalchemy
Installing collected packages: sqlalchemy
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 2.0.49
    Uninstalling SQLAlchemy-2.0.49:
      Successfully uninstalled SQLAlchemy-2.0.49
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-adk 1.29.0 requires sqlalchemy<3.0.0,>=2.0, but you have sqlalchemy 1.3.9 which is incompatible.
ipython-sql 0.5.0 requires sqlalchemy>=2.0, but you have sqlalchemy 1.3.9 which is incompatible.
alembic 1.18.4 requires SQLAlchemy>=1.4.23, but you have sqlalchemy 1.3.9 which is incompatible.
Successfully installed sqlalchemy-1.3.9
Requirement already satisfied: ipython-sql in /usr/local/lib/python3.12/dist-packages (0.5.0)
Requirement already satisfied: prettytable in /usr/local/lib/python3.12/dist-packages (from ipython-sql) (3.17.0)
Requirement already satisfied: ipython in /usr/local/lib/python3.12/dist-packages (from ipython-sql) (7.34.0)
Collecting sqlalchemy>=2.0 (from ipython-sql)
  Downloading sqlalchemy-2.0.49-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (9.5 kB)
Requirement already satisfied: sqlparse in /usr/local/lib/python3.12/dist-packages (from ipython-sql) (0.5.5)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from ipython-sql) (1.17.0)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.12/dist-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=2.0->ipython-sql) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=2.0->ipython-sql) (4.15.0)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (75.2.0)
Collecting jedi>=0.16 (from ipython->ipython-sql)
  Downloading jedi-0.19.2-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (5.7.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (3.0.52)
Requirement already satisfied: pygments in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (2.20.0)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (0.2.1)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (4.9.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prettytable->ipython-sql) (0.6.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/local/lib/python3.12/dist-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.6)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.12/dist-packages (from pexpect>4.3->ipython->ipython-sql) (0.7.0)
Downloading sqlalchemy-2.0.49-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (3.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 12.0 MB/s eta 0:00:00
Downloading jedi-0.19.2-py2.py3-none-any.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 46.1 MB/s eta 0:00:00
Installing collected packages: sqlalchemy, jedi
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 1.3.9
    Uninstalling SQLAlchemy-1.3.9:
      Successfully uninstalled SQLAlchemy-1.3.9
Successfully installed jedi-0.19.2 sqlalchemy-2.0.49
Requirement already satisfied: ipython-sql in /usr/local/lib/python3.12/dist-packages (0.5.0)
Requirement already satisfied: prettytable in /usr/local/lib/python3.12/dist-packages (3.17.0)
Requirement already satisfied: ipython in /usr/local/lib/python3.12/dist-packages (from ipython-sql) (7.34.0)
Requirement already satisfied: sqlalchemy>=2.0 in /usr/local/lib/python3.12/dist-packages (from ipython-sql) (2.0.49)
Requirement already satisfied: sqlparse in /usr/local/lib/python3.12/dist-packages (from ipython-sql) (0.5.5)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from ipython-sql) (1.17.0)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.12/dist-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prettytable) (0.6.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=2.0->ipython-sql) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=2.0->ipython-sql) (4.15.0)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (75.2.0)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (0.19.2)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (5.7.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (3.0.52)
Requirement already satisfied: pygments in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (2.20.0)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (0.2.1)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from ipython->ipython-sql) (4.9.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/local/lib/python3.12/dist-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.6)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.12/dist-packages (from pexpect>4.3->ipython->ipython-sql) (0.7.0)

In [2]:
import csv, sqlite3
import prettytable
prettytable.DEFAULT = 'DEFAULT'

con = sqlite3.connect("my_data1.db") #crea conexión
cur = con.cursor() #crea curso

In [3]:
!pip install -q pandas

In [4]:
%sql sqlite:///my_data1.db #conexión con sql

(sqlite3.OperationalError) near "#conexión": syntax error
[SQL: #conexión con sql]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [5]:
import pandas as pd

from google.colab import drive
drive.mount('/content/drive',force_remount=True)

url="/content/drive/MyDrive/dataset_part_2.csv" #Documento creado en parte 2
df=pd.read_csv(url)

Mounted at /content/drive

In [6]:
df.head()

,FlightNumber,Date,BoosterVersion,PayloadMass,Orbit,LaunchSite,Outcome,Flights,GridFins,Reused,Legs,LandingPad,Block,ReusedCount,Serial,Longitude,Latitude,Class
0,1,2010-06-04,Falcon 9,6123.547647,LEO,CCSFS SLC 40,None None,1,False,False,False,without landing pad,1.0,0,B0003,-80.577366,28.561857,0
1,2,2012-05-22,Falcon 9,525.000000,LEO,CCSFS SLC 40,None None,1,False,False,False,without landing pad,1.0,0,B0005,-80.577366,28.561857,0
2,3,2013-03-01,Falcon 9,677.000000,ISS,CCSFS SLC 40,None None,1,False,False,False,without landing pad,1.0,0,B0007,-80.577366,28.561857,0
3,4,2013-09-29,Falcon 9,500.000000,PO,VAFB SLC 4E,False Ocean,1,False,False,False,without landing pad,1.0,0,B1003,-120.610829,34.632093,0
4,5,2013-12-03,Falcon 9,3170.000000,GTO,CCSFS SLC 40,None None,1,False,False,False,without landing pad,1.0,0,B1004,-80.577366,28.561857,0

In [7]:
#Data frame a tabla sql
df.to_sql("SPACEXTBL", con, if_exists='replace', index=False,method="multi")
print(df)

    FlightNumber        Date BoosterVersion   PayloadMass Orbit    LaunchSite  \
0              1  2010-06-04       Falcon 9   6123.547647   LEO  CCSFS SLC 40
1              2  2012-05-22       Falcon 9    525.000000   LEO  CCSFS SLC 40
2              3  2013-03-01       Falcon 9    677.000000   ISS  CCSFS SLC 40
3              4  2013-09-29       Falcon 9    500.000000    PO   VAFB SLC 4E
4              5  2013-12-03       Falcon 9   3170.000000   GTO  CCSFS SLC 40
..           ...         ...            ...           ...   ...           ...
85            86  2020-09-03       Falcon 9  15600.000000  VLEO    KSC LC 39A
86            87  2020-10-06       Falcon 9  15600.000000  VLEO    KSC LC 39A
87            88  2020-10-18       Falcon 9  15600.000000  VLEO    KSC LC 39A
88            89  2020-10-24       Falcon 9  15600.000000  VLEO  CCSFS SLC 40
89            90  2020-11-05       Falcon 9   3681.000000   MEO  CCSFS SLC 40

        Outcome  Flights  GridFins  Reused   Legs                LandingPad  \
0     None None        1     False   False  False       without landing pad
1     None None        1     False   False  False       without landing pad
2     None None        1     False   False  False       without landing pad
3   False Ocean        1     False   False  False       without landing pad
4     None None        1     False   False  False       without landing pad
..          ...      ...       ...     ...    ...                       ...
85    True ASDS        2      True    True   True  5e9e3032383ecb6bb234e7ca
86    True ASDS        3      True    True   True  5e9e3032383ecb6bb234e7ca
87    True ASDS        6      True    True   True  5e9e3032383ecb6bb234e7ca
88    True ASDS        3      True    True   True  5e9e3033383ecbb9e534e7cc
89    True ASDS        1      True   False   True  5e9e3032383ecb6bb234e7ca

    Block  ReusedCount Serial   Longitude   Latitude  Class
0     1.0            0  B0003  -80.577366  28.561857      0
1     1.0            0  B0005  -80.577366  28.561857      0
2     1.0            0  B0007  -80.577366  28.561857      0
3     1.0            0  B1003 -120.610829  34.632093      0
4     1.0            0  B1004  -80.577366  28.561857      0
..    ...          ...    ...         ...        ...    ...
85    5.0           12  B1060  -80.603956  28.608058      1
86    5.0           13  B1058  -80.603956  28.608058      1
87    5.0           12  B1051  -80.603956  28.608058      1
88    5.0           12  B1060  -80.577366  28.561857      1
89    5.0            8  B1062  -80.577366  28.561857      1

[90 rows x 18 columns]

In [8]:
%sql DROP TABLE IF EXISTS SPACEXTABLE;

 * sqlite:///my_data1.db
Done.

[]

In [9]:
%sql create table SPACEXTABLE as select * from SPACEXTBL where "Date" is not null

 * sqlite:///my_data1.db
Done.

[]

### **Analisis exploratorio de datos con SQL**

In [10]:
# 1. Mostrar los nombres de los lugares de lanzamientos sin repeticiones

%sql select distinct "LaunchSite" from SPACEXTABLE

 * sqlite:///my_data1.db
Done.

[('CCSFS SLC 40',), ('VAFB SLC 4E',), ('KSC LC 39A',)]

In [11]:
# 2. Mostrar 5 registros donde los sitios de lanzamiento comienzan con la cadena "CCS"


%sql select * from SPACEXTABLE Where "LaunchSite" like "CCS%" limit 5

 * sqlite:///my_data1.db
Done.

[(1, '2010-06-04', 'Falcon 9', 6123.547647058824, 'LEO', 'CCSFS SLC 40', 'None None', 1, 0, 0, 0, 'without landing pad', 1.0, 0, 'B0003', -80.577366, 28.5618571, 0),
 (2, '2012-05-22', 'Falcon 9', 525.0, 'LEO', 'CCSFS SLC 40', 'None None', 1, 0, 0, 0, 'without landing pad', 1.0, 0, 'B0005', -80.577366, 28.5618571, 0),
 (3, '2013-03-01', 'Falcon 9', 677.0, 'ISS', 'CCSFS SLC 40', 'None None', 1, 0, 0, 0, 'without landing pad', 1.0, 0, 'B0007', -80.577366, 28.5618571, 0),
 (5, '2013-12-03', 'Falcon 9', 3170.0, 'GTO', 'CCSFS SLC 40', 'None None', 1, 0, 0, 0, 'without landing pad', 1.0, 0, 'B1004', -80.577366, 28.5618571, 0),
 (6, '2014-01-06', 'Falcon 9', 3325.0, 'GTO', 'CCSFS SLC 40', 'None None', 1, 0, 0, 0, 'without landing pad', 1.0, 0, 'B1005', -80.577366, 28.5618571, 0)]

In [12]:
#Lista los nombres de las series de Falcon 9  que tuvieron éxito en el aterrizaje en el barco en el océano y que tienen una masa de carga útil mayor que 4000 pero menor que 6000
%%sql
SELECT "Serial"
FROM SPACEXTABLE
WHERE "Outcome" = 'True Ocean'
AND "PayloadMass" BETWEEN 4000 AND 6000;

 * sqlite:///my_data1.db
Done.

[('B1032',)]

In [13]:
#Lista de posibles outcome

%sql select distinct "Outcome" from SPACEXTABLE

 * sqlite:///my_data1.db
Done.

[('None None',),
 ('False Ocean',),
 ('True Ocean',),
 ('False ASDS',),
 ('None ASDS',),
 ('True RTLS',),
 ('True ASDS',),
 ('False RTLS',)]

In [14]:
#Mosta la fecha del primer lanzamiento con aterrizaje exitoso en Oceano, ASDS, RTLS
%%sql
SELECT
    "Outcome",
    MIN("Date") AS first_success_date
FROM SPACEXTABLE
WHERE "Outcome" LIKE 'True%'
GROUP BY "Outcome";

 * sqlite:///my_data1.db
Done.

[('True ASDS', '2016-04-08'),
 ('True Ocean', '2014-04-18'),
 ('True RTLS', '2015-12-22')]

### **Analisis exploratorio de datos con Pyhton**

In [15]:
df.describe()

,FlightNumber,PayloadMass,Flights,Block,ReusedCount,Longitude,Latitude,Class
count,90.000000,90.000000,90.000000,90.000000,90.000000,90.000000,90.000000,90.000000
mean,45.500000,6123.547647,1.788889,3.500000,3.188889,-86.366477,29.449963,0.666667
std,26.124701,4732.115291,1.213172,1.595288,4.194417,14.149518,2.141306,0.474045
min,1.000000,350.000000,1.000000,1.000000,0.000000,-120.610829,28.561857,0.000000
25%,23.250000,2510.750000,1.000000,2.000000,0.000000,-80.603956,28.561857,0.000000
50%,45.500000,4701.500000,1.000000,4.000000,1.000000,-80.577366,28.561857,1.000000
75%,67.750000,8912.750000,2.000000,5.000000,4.000000,-80.577366,28.608058,1.000000
max,90.000000,15600.000000,6.000000,5.000000,13.000000,-80.577366,34.632093,1.000000

**1.** Numero de lanzamientos por sitio

In [16]:
# Numero de lanazamientos por sitio
df["LaunchSite"].value_counts()

LaunchSite
CCSFS SLC 40    55
KSC LC 39A      22
VAFB SLC 4E     13
Name: count, dtype: int64

- 55 lanzamientos fueron realizados desde  Cape Canaveral Space Launch Complex 40 (CCSFS SLC 40)
- 22 lanzamientos fueron realizados desde Kennedy Space Center Launch Complex 39A (KSC LC 39A)
- Y 13 fueron realizados desde Vandenberg Air Force Base Space Launch Complex 4E (VAFB SLC 4E)

**2.** Numero de veces a los que fue lanzado un coehete a cada orbita

In [17]:
# Numero de lanzamientos por orbita a la que se lanzaron sin contar GTO porque es solo estacionariaria
df[df['Orbit'] != 'GTO']['Orbit'].value_counts()

Orbit
ISS      21
VLEO     14
PO        9
LEO       7
SSO       5
MEO       3
HEO       1
ES-L1     1
SO        1
GEO       1
Name: count, dtype: int64

- LEO (Low Earth Orbit / Órbita terrestre baja):órbita cercana a la Tierra (hasta ~2,000 km), usada para satélites, observación y la ISS.

- VLEO (Very Low Earth Orbit / Órbita terrestre muy baja): Órbita aún más cercana (menos de ~450 km), usada para imágenes de muy alta resolución.

- GTO (Geostationary Transfer Orbit / Órbita de transferencia geoestacionaria): órbita intermedia entre LEO y GEO, se usa para llevar satélites a órbita geoestacionaria.

- SSO (Sun-Synchronous Orbit / Órbita heliosíncrona): Órbita polar que mantiene la misma hora solar al pasar, usada para satélites de clima y observación.

- ES-L1 (Punto Lagrange L1 Tierra-Sol): Punto donde se equilibran las fuerzas Tierra-Sol, permite observar el Sol de forma constante.

- HEO (Highly Elliptical Orbit / Órbita altamente elíptica): Órbita alargada alrededor de la Tierra.

- ISS (International Space Station / Estación Espacial Internacional): Estación habitable en órbita baja, usada para investigación científica.

- MEO (Medium Earth Orbit / Órbita media terrestre): Órbita entre LEO y GEO, usada para GPS y navegación.

- GEO (Geostationary Orbit / Órbita geoestacionaria): A ~35,786 km sobre el ecuador, usada para telecomunicaciones.

- PO (Polar Orbit / Órbita polar): Órbita que pasa por los polos.

**3.** Calcular frecuencia de exito o error en el resultado de la misión (aterrizaje)

In [18]:
landing_outcomes = df["Outcome"].value_counts()
landing_outcomes

Outcome
True ASDS      41
None None      19
True RTLS      14
False ASDS      6
True Ocean      5
False Ocean     2
None ASDS       2
False RTLS      1
Name: count, dtype: int64

- True Ocean: aterrizaje exitoso en una zona del océano
- False Ocean: aterrizaje fallido en el océano
- True RTLS: aterrizaje exitoso en plataforma terrestre
- False RTLS: aterrizaje fallido en plataforma terrestre
- True ASDS: aterrizaje exitoso en barco dron (drone ship)
- False ASDS: aterrizaje fallido en barco dron
- None ASDS / None None: fallo en el aterrizaje

EL aterrizaje con más frecuencia es exitoso en barco dron, seguido de los aterrizajes fallidos.

**5.** Promedio de exito

In [19]:
print("La tasa de exito es del :",df["Class"].mean()*100, "%") #Promedio de exito

La tasa de exito es del : 66.66666666666666 %