<a href="https://colab.research.google.com/github/ArlethSosa/Space-Y/blob/main/SPACE_Y_Parte_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Space Y**

## Parte 2

Manipulación de datos para análisis exploratorio de datos (EDA) para encontrar patrones en los datos

In [1]:
!pip install pandas
!pip install numpy

import pandas as pd
import numpy as np

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [2]:

from google.colab import drive
drive.mount('/content/drive')
df= pd.read_csv("/content/drive/MyDrive/API_SPACE_X.csv")
df.head()

Mounted at /content/drive

,FlightNumber,Date,BoosterVersion,PayloadMass,Orbit,LaunchSite,Outcome,Flights,GridFins,Reused,Legs,LandingPad,Block,ReusedCount,Serial,Longitude,Latitude
0,1,2010-06-04,Falcon 9,NaN,LEO,CCSFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0003,-80.577366,28.561857
1,2,2012-05-22,Falcon 9,525.0,LEO,CCSFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0005,-80.577366,28.561857
2,3,2013-03-01,Falcon 9,677.0,ISS,CCSFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B0007,-80.577366,28.561857
3,4,2013-09-29,Falcon 9,500.0,PO,VAFB SLC 4E,False Ocean,1,False,False,False,NaN,1.0,0,B1003,-120.610829,34.632093
4,5,2013-12-03,Falcon 9,3170.0,GTO,CCSFS SLC 40,None None,1,False,False,False,NaN,1.0,0,B1004,-80.577366,28.561857

### **Tratamiento de datos nulos**
Identificar los valores nulos para tratarlos

In [3]:
df.isnull().sum()

FlightNumber       0
Date               0
BoosterVersion     0
PayloadMass        5
Orbit              0
LaunchSite         0
Outcome            0
Flights            0
GridFins           0
Reused             0
Legs               0
LandingPad        26
Block              0
ReusedCount        0
Serial             0
Longitude          0
Latitude           0
dtype: int64

Tenemos 26 datos  de Landing Pad con datos nulos y 5 de payload Mass.

Para tratar los datos de Payload Mass, se calcula el promedio y remplazamos los valores nulos por el promedio

Por otra parte, para Landing Pad los valores nulos representan que no se utilizó una plataforma de aterrizaje por lo que se van a remplazar por "Sin plataforma"

In [4]:
 # Caluclar primedio de la columna PayloadMAss

mean = df["PayloadMass"].mean()

# Remplazar datos

df["PayloadMass"]= df["PayloadMass"].replace(np.nan, mean)

In [5]:
df["LandingPad"] = df["LandingPad"].replace(np.nan, "without landing pad")

Verificamos que ya no hay valores nulos

In [6]:
df.isnull().sum()

FlightNumber      0
Date              0
BoosterVersion    0
PayloadMass       0
Orbit             0
LaunchSite        0
Outcome           0
Flights           0
GridFins          0
Reused            0
Legs              0
LandingPad        0
Block             0
ReusedCount       0
Serial            0
Longitude         0
Latitude          0
dtype: int64

In [7]:
df["LandingPad"].head(100)

0          without landing pad
1          without landing pad
2          without landing pad
3          without landing pad
4          without landing pad
                ...
85    5e9e3032383ecb6bb234e7ca
86    5e9e3032383ecb6bb234e7ca
87    5e9e3032383ecb6bb234e7ca
88    5e9e3033383ecbb9e534e7cc
89    5e9e3032383ecb6bb234e7ca
Name: LandingPad, Length: 90, dtype: object

Identificar tipo de datos

In [8]:
df.dtypes

FlightNumber        int64
Date               object
BoosterVersion     object
PayloadMass       float64
Orbit              object
LaunchSite         object
Outcome            object
Flights             int64
GridFins             bool
Reused               bool
Legs                 bool
LandingPad         object
Block             float64
ReusedCount         int64
Serial             object
Longitude         float64
Latitude          float64
dtype: object

Creamos una nueva columan landing_class categorizando los valores de outcome de los aterrizajes

 0 para atterizajes fallidos

 1 para aterrizajes exitosos

In [9]:
landing_outcomes = df["Outcome"].value_counts()
landing_outcomes
for i,outcome in enumerate(landing_outcomes.keys()):
    print(i,outcome)

0 True ASDS
1 None None
2 True RTLS
3 False ASDS
4 True Ocean
5 False Ocean
6 None ASDS
7 False RTLS

In [10]:
""" Creamos una nueva columan landing_class categorizando los valores de outcome de los aterrizajes
 0 para atterizajes fallidos
 1 para aterrizajes exitosos
 """

landing_class=[]
bad_outcomes=set(landing_outcomes.keys()[[1,3,5,6,7]])

for i in df["Outcome"]:
  if i in bad_outcomes:
      landing_class.append(0)
  else:
      landing_class.append(1)
landing_class

[0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1]

In [11]:
# Agregamos la columna al dataframe
df['Class']=landing_class
df[['Class']].head(8)

   Class
0      0
1      0
2      0
3      0
4      0
5      0
6      1
7      1

In [12]:
df.head(5)

,FlightNumber,Date,BoosterVersion,PayloadMass,Orbit,LaunchSite,Outcome,Flights,GridFins,Reused,Legs,LandingPad,Block,ReusedCount,Serial,Longitude,Latitude,Class
0,1,2010-06-04,Falcon 9,6123.547647,LEO,CCSFS SLC 40,None None,1,False,False,False,without landing pad,1.0,0,B0003,-80.577366,28.561857,0
1,2,2012-05-22,Falcon 9,525.000000,LEO,CCSFS SLC 40,None None,1,False,False,False,without landing pad,1.0,0,B0005,-80.577366,28.561857,0
2,3,2013-03-01,Falcon 9,677.000000,ISS,CCSFS SLC 40,None None,1,False,False,False,without landing pad,1.0,0,B0007,-80.577366,28.561857,0
3,4,2013-09-29,Falcon 9,500.000000,PO,VAFB SLC 4E,False Ocean,1,False,False,False,without landing pad,1.0,0,B1003,-120.610829,34.632093,0
4,5,2013-12-03,Falcon 9,3170.000000,GTO,CCSFS SLC 40,None None,1,False,False,False,without landing pad,1.0,0,B1004,-80.577366,28.561857,0

Guardamos cambios en csv

In [13]:
df.to_csv("/content/drive/MyDrive/dataset_part_2.csv", index=False)